name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y clang clang-tidy valgrind

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run pytest
